#!/usr/bin/env ruby

$LIB_DIR = File.join(File.dirname(__FILE__), "lib")
$LOAD_PATH << $LIB_DIR 

require "collective"
require "pp"

load "network"

@hypervisor = Hypervisor.new

pp @hypervisor.list

g = Guest.new
g.name = "foo"
@hypervisor.create(g)


# pp @subnet.to_h
